package main

import (
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"time"
)

// validServiceName guards the operator-supplied compose --service NAME before
// it's interpolated as a YAML key, matching the rigor of validateProxyURL. (#52)
var validServiceName = regexp.MustCompile(`^[a-zA-Z0-9._-]+$`)

// dockerProxyArgs is the escrow wiring injected into a docker build.
type dockerProxyArgs struct {
	AddHost   string            // host.docker.internal:host-gateway
	BuildArgs map[string]string // proxy env + registry env
}

// deriveDockerArgs assembles the proxy/registry build-args for the given
// ecosystems. proxyHost is the build-reachable address of escrow (default
// host.docker.internal); egressPort is escrow's egress-proxy port;
// mirrorPort is escrow's mirror port (default 7888).
func deriveDockerArgs(ecosystems []string, proxyHost string, egressPort, mirrorPort int) dockerProxyArgs {
	mirrorBase := fmt.Sprintf("http://%s:%d", proxyHost, mirrorPort)
	proxyURL := fmt.Sprintf("http://%s:%d", proxyHost, egressPort)
	noProxy := proxyHost + ",localhost,127.0.0.1"

	ba := map[string]string{
		"HTTP_PROXY":  proxyURL,
		"HTTPS_PROXY": proxyURL,
		"http_proxy":  proxyURL,
		"https_proxy": proxyURL,
		"NO_PROXY":    noProxy,
		"no_proxy":    noProxy,
	}
	for _, e := range buildEnvVars(ecosystems, mirrorBase) {
		ba[e.key] = e.value
	}
	return dockerProxyArgs{AddHost: proxyHost + ":host-gateway", BuildArgs: ba}
}

func sortedKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

// parseDockerFlags extracts escrow flags and returns the remaining (user) args.
func parseDockerFlags(args []string) (ecosystems []string, proxyHost string, egressPort, mirrorPort int, rest []string) {
	fs := flag.NewFlagSet("docker", flag.ExitOnError)
	ecoStr := fs.String("ecosystems", "npm,pypi,go", "comma-separated ecosystems")
	host := fs.String("proxy-host", "host.docker.internal", "build-reachable escrow host")
	port := fs.Int("egress-port", 7889, "escrow egress-proxy port")
	mport := fs.Int("mirror-port", 7888, "escrow mirror port")
	_ = fs.Parse(args)
	return parseEcosystems(*ecoStr), *host, *port, *mport, fs.Args()
}

func runDocker(args []string) {
	if len(args) == 0 {
		fmt.Fprintln(os.Stderr, "usage: escrow-cli docker <check|build|compose> ...")
		os.Exit(2)
	}
	switch args[0] {
	case "check":
		runDockerCheck(args[1:])
	case "build":
		runDockerBuild(args[1:])
	case "compose":
		runDockerCompose(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown docker subcommand %q\n", args[0])
		os.Exit(2)
	}
}

func runDockerCheck(args []string) {
	ecos, proxyHost, egressPort, mirrorPort, _ := parseDockerFlags(args)
	da := deriveDockerArgs(ecos, proxyHost, egressPort, mirrorPort)
	fmt.Printf("--add-host %s\n", da.AddHost)
	for _, k := range sortedKeys(da.BuildArgs) {
		fmt.Printf("--build-arg %s='%s'\n", k, da.BuildArgs[k])
	}
	client := &http.Client{Timeout: 2 * time.Second}
	if resp, err := client.Get("http://127.0.0.1:7888/healthz"); err == nil {
		_ = resp.Body.Close()
		fmt.Println("escrow mirror: reachable on the host (127.0.0.1:7888) — note: a Linux build container reaches escrow via host.docker.internal only if escrow binds 0.0.0.0/the docker gateway")
	} else {
		fmt.Println("escrow mirror: NOT reachable on the host (127.0.0.1:7888) — start escrow first")
	}
}

// dockerBuildArgv assembles the full `docker build ...` argument vector
// (escrow wiring first, then the user's args). Build-args are emitted in a
// stable (sorted) order for determinism.
func dockerBuildArgv(da dockerProxyArgs, userArgs []string) []string {
	argv := []string{"build", "--add-host", da.AddHost}
	for _, k := range sortedKeys(da.BuildArgs) {
		argv = append(argv, "--build-arg", k+"="+da.BuildArgs[k])
	}
	return append(argv, userArgs...)
}

func runDockerBuild(args []string) {
	ecos, proxyHost, egressPort, mirrorPort, userArgs := parseDockerFlags(args)
	da := deriveDockerArgs(ecos, proxyHost, egressPort, mirrorPort)
	argv := dockerBuildArgv(da, userArgs)

	cmd := exec.Command("docker", argv...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "docker build failed: %v\n", err)
		os.Exit(1)
	}
}

// composeOverride renders a docker-compose override that routes each named
// service's build through escrow (advisory HTTP_PROXY + registry env + host-gateway).
func composeOverride(services []string, da dockerProxyArgs) string {
	var b strings.Builder
	b.WriteString("# Generated by `escrow-cli docker compose init`. Include with:\n")
	b.WriteString("#   docker compose -f docker-compose.yml -f docker-compose.escrow.yml build\n")
	b.WriteString("services:\n")
	for _, s := range services {
		fmt.Fprintf(&b, "  %s:\n    build:\n      args:\n", s)
		for _, k := range sortedKeys(da.BuildArgs) {
			fmt.Fprintf(&b, "        %s: %q\n", k, da.BuildArgs[k])
		}
		b.WriteString("      extra_hosts:\n")
		fmt.Fprintf(&b, "        - %q\n", da.AddHost)
	}
	return b.String()
}

func runDockerCompose(args []string) {
	if len(args) == 0 || args[0] != "init" {
		fmt.Fprintln(os.Stderr, "usage: escrow-cli docker compose init --service NAME [--service NAME] [flags]")
		os.Exit(2)
	}
	rest := args[1:]
	var services []string
	var passthrough []string
	for i := 0; i < len(rest); i++ {
		if rest[i] == "--service" && i+1 < len(rest) {
			name := rest[i+1]
			if !validServiceName.MatchString(name) {
				fmt.Fprintf(os.Stderr, "invalid --service %q: must match %s\n", name, validServiceName.String())
				os.Exit(2)
			}
			services = append(services, name)
			i++
			continue
		}
		passthrough = append(passthrough, rest[i])
	}
	if len(services) == 0 {
		fmt.Fprintln(os.Stderr, "at least one --service NAME is required")
		os.Exit(2)
	}
	ecos, proxyHost, egressPort, mirrorPort, _ := parseDockerFlags(passthrough)
	da := deriveDockerArgs(ecos, proxyHost, egressPort, mirrorPort)

	const out = "docker-compose.escrow.yml"
	if _, err := os.Stat(out); err == nil {
		if err := os.Rename(out, out+".escrow-backup"); err != nil {
			fmt.Fprintf(os.Stderr, "backup %s: %v\n", out, err)
			os.Exit(1)
		}
	}
	if err := os.WriteFile(out, []byte(composeOverride(services, da)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", out, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s for services: %s\n", out, strings.Join(services, ", "))
}
