package main

import (
	"fmt"
	"regexp"
	"strings"
)

var registryHosts = map[string][]string{
	"npm":      {"registry.npmjs.org", "npm.pkg.github.com"},
	"pypi":     {"pypi.org", "files.pythonhosted.org"},
	"go":       {"proxy.golang.org", "sum.golang.org"},
	"cargo":    {"static.crates.io", "index.crates.io"},
	"nuget":    {"api.nuget.org"},
	"maven":    {"repo.maven.apache.org", "repo1.maven.org"},
	"composer": {"repo.packagist.org", "packagist.org"},
}

var allEcosystems = []string{"npm", "pypi", "go", "cargo", "nuget", "maven", "composer"}

// validUnixUser matches standard macOS/BSD service account names.
var validUnixUser = regexp.MustCompile(`^[a-z_][a-z0-9_-]{0,31}$`)

func parseEcosystems(s string) []string {
	valid := make(map[string]bool, len(allEcosystems))
	for _, e := range allEcosystems {
		valid[e] = true
	}
	seen := make(map[string]bool)
	var result []string
	for _, e := range strings.Split(s, ",") {
		e = strings.TrimSpace(strings.ToLower(e))
		if valid[e] && !seen[e] {
			result = append(result, e)
			seen[e] = true
		}
	}
	return result
}

// buildPfRules generates pf anchor content for the given ecosystems.
// proxyUser must be a numeric UID string (not a username) — pf resolves
// usernames at load time via the system user database, which may not yet
// reflect a freshly-created account. Numeric UIDs bypass that lookup.
// Pass rules appear before block rules — required by pf evaluation order.
// inet6 block rules are intentionally omitted: pf fails to expand them for
// hostnames that have no AAAA record, which aborts the entire anchor load.
func buildPfRules(ecosystems []string, proxyPort int, proxyUID string) string {
	var sb strings.Builder
	sb.WriteString("# Escrow redirect rules — generated by escrow-cli\n\n")

	for _, eco := range ecosystems {
		fmt.Fprintf(&sb, "# %s\n", eco)
		for _, host := range registryHosts[eco] {
			fmt.Fprintf(&sb, "rdr pass inet proto tcp from any to %s port 443 -> 127.0.0.1 port %d\n",
				host, proxyPort)
		}
	}
	sb.WriteString("\n")

	hosts := orderedHosts(ecosystems)
	sb.WriteString("# pass proxy upstream connections (matched by UID to survive OD cache delay)\n")
	for _, host := range hosts {
		fmt.Fprintf(&sb, "pass out quick proto tcp from any to %s port {80, 443} user %s\n",
			host, proxyUID)
	}
	sb.WriteString("\n")

	sb.WriteString("# block port-80 bypass (IPv4 only)\n")
	for _, host := range hosts {
		fmt.Fprintf(&sb, "block return out inet proto tcp from any to %s port 80\n", host)
	}

	return sb.String()
}

func orderedHosts(ecosystems []string) []string {
	seen := make(map[string]bool)
	var hosts []string
	for _, eco := range ecosystems {
		for _, h := range registryHosts[eco] {
			if !seen[h] {
				seen[h] = true
				hosts = append(hosts, h)
			}
		}
	}
	return hosts
}
