package main

import (
	"fmt"
	"net"
	"regexp"
	"strings"
)

var registryHosts = map[string][]string{
	"npm":      {"registry.npmjs.org", "npm.pkg.github.com"},
	"pypi":     {"pypi.org", "files.pythonhosted.org"},
	"go":       {"proxy.golang.org", "sum.golang.org"},
	"cargo":    {"static.crates.io", "index.crates.io"},
	"nuget":    {"api.nuget.org"},
	"maven":    {"repo.maven.apache.org", "repo1.maven.org"},
	"composer": {"repo.packagist.org", "packagist.org"},
}

var allEcosystems = []string{"npm", "pypi", "go", "cargo", "nuget", "maven", "composer"}

// validUnixUser matches standard macOS/BSD service account names.
var validUnixUser = regexp.MustCompile(`^[a-z_][a-z0-9_-]{0,31}$`)

func parseEcosystems(s string) []string {
	valid := make(map[string]bool, len(allEcosystems))
	for _, e := range allEcosystems {
		valid[e] = true
	}
	seen := make(map[string]bool)
	var result []string
	for _, e := range strings.Split(s, ",") {
		e = strings.TrimSpace(strings.ToLower(e))
		if valid[e] && !seen[e] {
			result = append(result, e)
			seen[e] = true
		}
	}
	return result
}

// buildPfRules generates pf anchor content for the given ecosystems.
// proxyUID must be a numeric UID string — pf resolves usernames at load time
// via getpwnam() which may not see a freshly-created OD account.
// Pass rules appear before block rules — required by pf evaluation order.
// When blockIPv6 is false (default), inet6 block rules are generated only for
// hosts that currently have AAAA records — pf aborts the entire anchor load
// with "no valid combination" if an inet6 rule targets a hostname with no IPv6
// address. That fails open for a host that gains an AAAA later. When blockIPv6
// is true, a single host-independent rule blocks ALL IPv6 egress to :80/:443
// (except the proxy UID), closing that gap at the cost of the host's general
// IPv6 web traffic on those ports.
func buildPfRules(ecosystems []string, proxyPort int, proxyUID string, blockIPv6 bool) string {
	var sb strings.Builder
	sb.WriteString("# Escrow redirect rules — generated by escrow-cli\n\n")

	hosts := orderedHosts(ecosystems)

	// Resolve which hosts have AAAA records right now.
	hasIPv6 := make(map[string]bool, len(hosts))
	for _, h := range hosts {
		addrs, err := net.LookupHost(h)
		if err == nil {
			for _, a := range addrs {
				if strings.Contains(a, ":") { // IPv6 address
					hasIPv6[h] = true
					break
				}
			}
		}
	}

	// rdr rules — IPv4 redirect to proxy.
	for _, eco := range ecosystems {
		fmt.Fprintf(&sb, "# %s\n", eco)
		for _, host := range registryHosts[eco] {
			fmt.Fprintf(&sb, "rdr pass inet proto tcp from any to %s port 443 -> 127.0.0.1 port %d\n",
				host, proxyPort)
		}
	}
	sb.WriteString("\n")

	// pass rules — exempt proxy UID from redirect (must come before block rules).
	sb.WriteString("# pass proxy upstream connections\n")
	for _, host := range hosts {
		fmt.Fprintf(&sb, "pass out quick proto tcp from any to %s port {80, 443} user %s\n",
			host, proxyUID)
	}
	sb.WriteString("\n")

	// block rules — prevent port-80 and IPv6 bypass.
	sb.WriteString("# block bypass\n")
	for _, host := range hosts {
		fmt.Fprintf(&sb, "block return out inet  proto tcp from any to %s port 80\n", host)
		if !blockIPv6 && hasIPv6[host] {
			fmt.Fprintf(&sb, "block return out inet6 proto tcp from any to %s port 80\n", host)
			fmt.Fprintf(&sb, "block return out inet6 proto tcp from any to %s port 443\n", host)
		}
	}

	// --block-ipv6: a host-independent IPv6 cutoff that does not depend on any
	// host having an AAAA at load time, so a later-acquired AAAA cannot bypass.
	// The quick pass for the proxy UID lets escrow's own upstream IPv6 through.
	if blockIPv6 {
		sb.WriteString("\n# block all IPv6 egress to web ports except the proxy (--block-ipv6)\n")
		fmt.Fprintf(&sb, "pass out quick inet6 proto tcp from any to any port {80, 443} user %s\n", proxyUID)
		sb.WriteString("block return out inet6 proto tcp from any to any port {80, 443}\n")
	}

	return sb.String()
}

func orderedHosts(ecosystems []string) []string {
	seen := make(map[string]bool)
	var hosts []string
	for _, eco := range ecosystems {
		for _, h := range registryHosts[eco] {
			if !seen[h] {
				seen[h] = true
				hosts = append(hosts, h)
			}
		}
	}
	return hosts
}
