package config

import (
	"crypto/rand"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

type Config struct {
	Server        ServerConfig    `toml:"server"`
	Storage       StorageConfig   `toml:"storage"`
	Policy        *PolicyConfig   `toml:"policy"`
	Ecosystems    EcosystemConfig `toml:"ecosystems"`
	Alerts        AlertsConfig    `toml:"alerts"`
	Dashboard     DashboardConfig `toml:"dashboard"`
	AllowlistPath string          `toml:"allowlist_path"`
	BlocklistPath string          `toml:"blocklist_path"`
}

type ServerConfig struct {
	Host     string `toml:"host"`
	Port     int    `toml:"port"`
	LogLevel string `toml:"log_level"`
}

type StorageConfig struct {
	Backend string     `toml:"backend"`
	Disk    DiskConfig `toml:"disk"`
	S3      S3Config   `toml:"s3"`
}

type DiskConfig struct {
	Path string `toml:"path"`
}

type S3Config struct {
	Bucket   string `toml:"bucket"`
	Region   string `toml:"region"`
	Endpoint string `toml:"endpoint"`
}

type PolicyConfig struct {
	Age        *AgePolicyConfig        `toml:"age"`
	OSV        *OSVPolicyConfig        `toml:"osv"`
	Publisher  *PublisherPolicyConfig  `toml:"publisher"`
	Popularity *PopularityPolicyConfig `toml:"popularity"`
	PyPI       *PyPIPolicyConfig       `toml:"pypi"`
}

type AgePolicyConfig struct {
	MinDays int    `toml:"min_days"`
	Action  string `toml:"action"`
}

type OSVPolicyConfig struct {
	MinSeverity string `toml:"min_severity"`
	Action      string `toml:"action"`
}

type PublisherPolicyConfig struct {
	MaxAccountAgeDays int    `toml:"max_account_age_days"`
	Action            string `toml:"action"`
}

type PopularityPolicyConfig struct {
	SpikeFactor float64 `toml:"spike_factor"`
	Action      string  `toml:"action"`
}

type PyPIPolicyConfig struct {
	BlockSdist bool `toml:"block_sdist"`
}

type EcosystemConfig struct {
	NPM      bool `toml:"npm"`
	PyPI     bool `toml:"pypi"`
	Go       bool `toml:"go"`
	Cargo    bool `toml:"cargo"`
	Composer bool `toml:"composer"`
}

type AlertsConfig struct {
	WebhookURL string `toml:"webhook_url"`
}

type DashboardConfig struct {
	Enabled  bool   `toml:"enabled"`
	Path     string `toml:"path"`
	Username string `toml:"username"`
	Password string `toml:"password"`
	Secret   string `toml:"secret"`
}

func DefaultConfig() Config {
	return Config{
		Server:     ServerConfig{Host: "0.0.0.0", Port: 8888, LogLevel: "info"},
		Storage:    StorageConfig{Backend: "disk", Disk: DiskConfig{Path: "./sentinel-cache"}},
		Ecosystems: EcosystemConfig{NPM: true, PyPI: true, Go: false, Cargo: false, Composer: false},
		Dashboard:  DashboardConfig{Enabled: true, Path: "/dashboard"},
	}
}

func Load(path string) (Config, error) {
	cfg := DefaultConfig()
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return cfg, nil
	}
	if _, err := toml.DecodeFile(path, &cfg); err != nil {
		return Config{}, fmt.Errorf("parse config %s: %w", path, err)
	}
	return cfg, nil
}

func GenerateIfMissing(path string) (bool, string, error) {
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		return false, "", nil
	}
	secret, err := randomHex(32)
	if err != nil {
		return false, "", fmt.Errorf("generate secret: %w", err)
	}
	password, err := randomAlpha(12)
	if err != nil {
		return false, "", fmt.Errorf("generate password: %w", err)
	}
	cfg := DefaultConfig()
	content := fmt.Sprintf(`# Generated by escrow on first boot.

[server]
  host      = %q
  port      = %d
  log_level = %q

[storage]
  backend = "disk"
  [storage.disk]
    path = "./escrow-cache"

[ecosystems]
  npm      = true
  pypi     = true
  go       = false
  cargo    = false
  composer = false

[dashboard]
  enabled  = true
  path     = "/dashboard"
  username = "admin"
  password = %q
  secret   = %q

[alerts]
  webhook_url = ""

allowlist_path = "escrow-allowlist.json"
blocklist_path = "escrow-blocklist.json"
`,
		cfg.Server.Host, cfg.Server.Port, cfg.Server.LogLevel,
		password, secret,
	)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return false, "", fmt.Errorf("write config: %w", err)
	}
	msg := fmt.Sprintf("Generated %s\n  username: admin\n  password: %s\n  url:      http://localhost:%d%s",
		path, password, cfg.Server.Port, cfg.Dashboard.Path)
	return true, msg, nil
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", b), nil
}

func randomAlpha(n int) (string, error) {
	const chars = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	for i := range b {
		b[i] = chars[int(b[i])%len(chars)]
	}
	return string(b), nil
}

func (c Config) Warnings() []string {
	var w []string
	if c.Policy == nil {
		w = append(w, "no policy configured — sentinel is proxying without age gate, OSV scanning, or trust checks. Add a [policy] section to sentinel.toml to enable protection.")
	}
	if c.Storage.Backend == "memory" {
		w = append(w, "storage backend is 'memory' — no packages will be cached between restarts.")
	}
	return w
}
